---

- name: Deny access to AWS Instance Metadata Service (IMDSv1, IMDSv2)
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

  - iptables_raw:
    name: block_imds
    rules: "-A OUTPUT -m owner ! --uid-owner root -d 169.254.169.254 -j DROP"
