---

- name: Deny access to AWS Instance Metadata Service (IMDSv1, IMDSv2)
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

  - name: Block access to IMDS for non-root users
    iptables:
      chain: OUTPUT
      destination: 169.254.169.254
      uid_owner: !0
      action: insert
      jump: DROP
